# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_postmodel_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
